#!/bin/bash
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
export CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH:-${SCRIPT_DIR}/sysroot}"
#Release Debug
cmake -DCMAKE_BUILD_TYPE:STRING="Release" -DIMPORT_GTEST=OFF -DONLY_GENERATE_FUNDAMENTAL_DEPS=ON -DFUNDAMENTAL_ENABLE_SCRIPT_SUPPORT=ON -DIMPORT_BENCHMARK=OFF -DFUNDAMENTAL_BUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=${CMAKE_PREFIX_PATH} -S . -B ./build-linux-install
